<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TCGLooker.Worker</RootNamespace>
    <UserSecretsId>e06c7eaf-e101-4cdd-8d31-80e9bc229b66</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\TCGLooker.Application\TCGLooker.Application.csproj" />
    <ProjectReference Include="..\TCGLooker.Infra\TCGLooker.Infra.csproj" />
  </ItemGroup>

</Project>
