<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>TCGLooker.Api</RootNamespace>
        <AssemblyName>TCGLooker.Api</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TCGLooker.Application\TCGLooker.Application.csproj" />
        <ProjectReference Include="..\TCGLooker.Infra\TCGLooker.Infra.csproj" />
    </ItemGroup>

</Project>
